### ISSUE TITLE
How to show suggestions before typing

### ISSUE THREAD

**Issue by joedborg** [maxwells/bootstrap-tags#65]
For example, if I have 
```javascript
suggestions: ['Apple', 'Adam', 'Ace']
```
I will no see any of these until I type `a` into the input.  Is there any way to get these all to show on focus?

**Comment by maxwells** [comment]
Sorry that this wasn't documented. The `suggestOnClick` flag has you covered:

```javascript
$('#my-tag-list').tags({
    suggestions: ['Apple', 'Adam', 'Ace'],
    suggestOnClick: true,
});
```

**Comment by joedborg** [comment]
Perfect, thanks!

**Comment by joedborg** [comment]
Have raised a pull request to add to README
